"""add_generated_images_table_for_image_gallery

Revision ID: 1372f6e4ef76
Revises: d09fab6f7e52
Create Date: 2025-12-24 14:19:30.809353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1372f6e4ef76'
down_revision: Union[str, Sequence[str], None] = 'd09fab6f7e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_images',
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('image_data', sa.Text(), nullable=False),
    sa.Column('thumbnail_data', sa.Text(), nullable=True),
    sa.Column('image_format', sa.String(length=10), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_images_is_favorite'), 'generated_images', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_generated_images_project_id'), 'generated_images', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_images_project_id'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_is_favorite'), table_name='generated_images')
    op.drop_table('generated_images')
    # ### end Alembic commands ###
