"""Add research task and research source tables

Revision ID: 2904c3476915
Revises: d3bd349b1741
Create Date: 2025-12-17 00:46:27.169354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2904c3476915'
down_revision: Union[str, Sequence[str], None] = 'd3bd349b1741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_tasks',
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('max_sources', sa.Integer(), nullable=False),
    sa.Column('depth', sa.String(length=20), nullable=False),
    sa.Column('source_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sources_found', sa.Integer(), nullable=False),
    sa.Column('sources_scraped', sa.Integer(), nullable=False),
    sa.Column('sources_added', sa.Integer(), nullable=False),
    sa.Column('sources_failed', sa.Integer(), nullable=False),
    sa.Column('sources_skipped', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('estimated_time_remaining', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contradictions_found', sa.Integer(), nullable=False),
    sa.Column('suggested_followups', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_tasks_status'), 'research_tasks', ['status'], unique=False)
    op.create_table('research_sources',
    sa.Column('research_task_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=True),
    sa.Column('credibility_reasons', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sources_research_task_id'), 'research_sources', ['research_task_id'], unique=False)
    op.create_index(op.f('ix_research_sources_status'), 'research_sources', ['status'], unique=False)
    op.add_column('documents', sa.Column('source_type', sa.String(length=50), nullable=False, server_default='upload'))
    op.add_column('documents', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('published_date', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('credibility_score', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('research_task_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_documents_research_task_id'), 'documents', ['research_task_id'], unique=False)
    op.create_index(op.f('ix_documents_source_type'), 'documents', ['source_type'], unique=False)
    op.create_foreign_key(None, 'documents', 'research_tasks', ['research_task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_source_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_research_task_id'), table_name='documents')
    op.drop_column('documents', 'research_task_id')
    op.drop_column('documents', 'credibility_score')
    op.drop_column('documents', 'published_date')
    op.drop_column('documents', 'author')
    op.drop_column('documents', 'source_url')
    op.drop_column('documents', 'source_type')
    op.drop_index(op.f('ix_research_sources_status'), table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_research_task_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_research_tasks_status'), table_name='research_tasks')
    op.drop_table('research_tasks')
    # ### end Alembic commands ###
