"""Add semantic metadata to chunks

Revision ID: 310a1193bdaf
Revises: c9c06f1560db
Create Date: 2025-12-16 01:02:15.659516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310a1193bdaf'
down_revision: Union[str, Sequence[str], None] = 'c9c06f1560db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('content_type', sa.String(length=50), nullable=True))
    op.add_column('chunks', sa.Column('heading_hierarchy', sa.JSON(), nullable=True))
    op.add_column('chunks', sa.Column('section_title', sa.String(length=500), nullable=True))
    op.add_column('chunks', sa.Column('has_code', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('semantic_density', sa.Float(), nullable=True))
    op.create_index(op.f('ix_chunks_section_title'), 'chunks', ['section_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_section_title'), table_name='chunks')
    op.drop_column('chunks', 'semantic_density')
    op.drop_column('chunks', 'has_code')
    op.drop_column('chunks', 'section_title')
    op.drop_column('chunks', 'heading_hierarchy')
    op.drop_column('chunks', 'content_type')
    # ### end Alembic commands ###
