"""Add YouTube video model and extend Chunk with youtube_video_id

Revision ID: 3988218a7e66
Revises: ba0350382b81
Create Date: 2025-12-16 20:41:43.682373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3988218a7e66'
down_revision: Union[str, Sequence[str], None] = 'ba0350382b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_videos',
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('channel', sa.String(length=255), nullable=True),
    sa.Column('channel_id', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.String(length=8), nullable=True),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('transcript_language', sa.String(length=10), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_videos_video_id'), 'youtube_videos', ['video_id'], unique=True)
    op.add_column('chunks', sa.Column('youtube_video_id', sa.String(length=36), nullable=True))
    op.drop_index(op.f('ix_chunks_document_index'), table_name='chunks')
    op.create_index(op.f('ix_chunks_youtube_video_id'), 'chunks', ['youtube_video_id'], unique=False)
    op.create_foreign_key(None, 'chunks', 'youtube_videos', ['youtube_video_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_pinned_updated'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_updated_desc'), table_name='conversations')
    op.drop_index(op.f('ix_messages_conversation_created'), table_name='messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messages_conversation_created'), 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversations_updated_desc'), 'conversations', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('ix_conversations_pinned_updated'), 'conversations', ['is_pinned', sa.literal_column('updated_at DESC')], unique=False)
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_index(op.f('ix_chunks_youtube_video_id'), table_name='chunks')
    op.create_index(op.f('ix_chunks_document_index'), 'chunks', ['document_id', 'chunk_index'], unique=False)
    op.drop_column('chunks', 'youtube_video_id')
    op.drop_index(op.f('ix_youtube_videos_video_id'), table_name='youtube_videos')
    op.drop_table('youtube_videos')
    # ### end Alembic commands ###
