"""Add token_count to messages for context tracking

Revision ID: 77a15ccbb43a
Revises: 310a1193bdaf
Create Date: 2025-12-16 13:43:33.663002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a15ccbb43a'
down_revision: Union[str, Sequence[str], None] = '310a1193bdaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('token_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'token_count')
    # ### end Alembic commands ###
