"""Add research projects and briefings tables for Research Autopilot

Revision ID: 854629751977
Revises: 2904c3476915
Create Date: 2025-12-18 17:02:29.338494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '854629751977'
down_revision: Union[str, Sequence[str], None] = '2904c3476915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_generate_tasks', sa.Boolean(), nullable=False),
    sa.Column('max_tasks_per_run', sa.Integer(), nullable=False),
    sa.Column('default_max_sources', sa.Integer(), nullable=False),
    sa.Column('default_depth', sa.String(length=20), nullable=False),
    sa.Column('default_source_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('failed_tasks', sa.Integer(), nullable=False),
    sa.Column('total_sources_added', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_projects_name'), 'research_projects', ['name'], unique=False)
    op.create_index(op.f('ix_research_projects_status'), 'research_projects', ['status'], unique=False)
    op.create_table('research_briefings',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contradictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('knowledge_gaps', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('suggested_tasks', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('task_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_briefings_project_id'), 'research_briefings', ['project_id'], unique=False)
    op.add_column('research_tasks', sa.Column('project_id', sa.String(length=36), nullable=True))

    # Add auto_generated column with default value for existing rows
    op.add_column('research_tasks', sa.Column('auto_generated', sa.Boolean(), nullable=True))
    op.execute('UPDATE research_tasks SET auto_generated = false WHERE auto_generated IS NULL')
    op.alter_column('research_tasks', 'auto_generated', nullable=False)

    op.add_column('research_tasks', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_research_tasks_project_id'), 'research_tasks', ['project_id'], unique=False)
    op.create_foreign_key(None, 'research_tasks', 'research_projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_research_tasks_project_id'), table_name='research_tasks')
    op.drop_column('research_tasks', 'scheduled_at')
    op.drop_column('research_tasks', 'auto_generated')
    op.drop_column('research_tasks', 'project_id')
    op.drop_index(op.f('ix_research_briefings_project_id'), table_name='research_briefings')
    op.drop_table('research_briefings')
    op.drop_index(op.f('ix_research_projects_status'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_name'), table_name='research_projects')
    op.drop_table('research_projects')
    # ### end Alembic commands ###
