"""Add tags and note_tags tables with many-to-many relationship

Revision ID: 9444033aad25
Revises: d0046533c76c
Create Date: 2025-12-15 18:02:26.136283

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '9444033aad25'
down_revision: Union[str, Sequence[str], None] = 'd0046533c76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('note_tags',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'tag_id')
    )
    # ### end Alembic commands ###

    # Data migration: Convert existing comma-separated tags to normalized format
    conn = op.get_bind()

    # Get all notes with tags
    notes = conn.execute(text("SELECT id, tags FROM notes WHERE tags IS NOT NULL AND tags != ''")).fetchall()

    # Dictionary to track tag name -> tag id mapping
    tag_map = {}

    for note in notes:
        note_id, tags_str = note
        if not tags_str:
            continue

        # Parse comma-separated tags
        tag_names = [tag.strip().lower() for tag in tags_str.split(',') if tag.strip()]

        for tag_name in tag_names:
            # Get or create tag
            if tag_name not in tag_map:
                # Check if tag already exists
                existing = conn.execute(
                    text("SELECT id FROM tags WHERE name = :name"),
                    {"name": tag_name}
                ).fetchone()

                if existing:
                    tag_map[tag_name] = existing[0]
                else:
                    # Create new tag
                    tag_id = str(uuid.uuid4())
                    conn.execute(
                        text("INSERT INTO tags (id, name) VALUES (:id, :name)"),
                        {"id": tag_id, "name": tag_name}
                    )
                    tag_map[tag_name] = tag_id

            # Create note-tag association
            tag_id = tag_map[tag_name]
            conn.execute(
                text("INSERT INTO note_tags (note_id, tag_id) VALUES (:note_id, :tag_id) ON CONFLICT DO NOTHING"),
                {"note_id": note_id, "tag_id": tag_id}
            )

    # Keep the old tags column for backward compatibility (can be removed in a future migration)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
