"""Create conceptual_snapshots table

Revision ID: c32314510b0f
Revises: 63d22e19faa2
Create Date: 2025-12-16 22:49:43.154852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32314510b0f'
down_revision: Union[str, Sequence[str], None] = '63d22e19faa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'conceptual_snapshots',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('topic', sa.String(length=500), nullable=False),
        sa.Column('understanding', sa.Text(), nullable=False),
        sa.Column('key_concepts', sa.ARRAY(sa.String()), nullable=False),
        sa.Column('misconceptions', sa.ARRAY(sa.String()), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('questions_asked', sa.ARRAY(sa.String()), nullable=False),
        sa.Column('conversation_id', sa.String(length=36), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conceptual_snapshots_topic'), 'conceptual_snapshots', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conceptual_snapshots_topic'), table_name='conceptual_snapshots')
    op.drop_table('conceptual_snapshots')
    # ### end Alembic commands ###
