"""add suggested_questions to messages

Revision ID: c9c06f1560db
Revises: b997ac433611
Create Date: 2025-12-16 00:36:37.250611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c06f1560db'
down_revision: Union[str, Sequence[str], None] = 'b997ac433611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('suggested_questions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'suggested_questions')
    # ### end Alembic commands ###
