"""Add metadata field to Message model

Revision ID: d09fab6f7e52
Revises: d5f76ea5b82f
Create Date: 2025-12-23 15:11:49.157019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09fab6f7e52'
down_revision: Union[str, Sequence[str], None] = 'd5f76ea5b82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'metadata')
    # ### end Alembic commands ###
