"""Add category field to documents

Revision ID: d3bd349b1741
Revises: c32314510b0f
Create Date: 2025-12-17 00:43:40.651055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3bd349b1741'
down_revision: Union[str, Sequence[str], None] = 'c32314510b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conceptual_snapshots_topic'), table_name='conceptual_snapshots')
    op.drop_table('conceptual_snapshots')
    op.add_column('documents', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_column('documents', 'category')
    op.create_table('conceptual_snapshots',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('understanding', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_concepts', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('misconceptions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('questions_asked', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('conceptual_snapshots_conversation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('conceptual_snapshots_pkey'))
    )
    op.create_index(op.f('ix_conceptual_snapshots_topic'), 'conceptual_snapshots', ['topic'], unique=False)
    # ### end Alembic commands ###
