"""add archive fields to documents

Revision ID: d5f76ea5b82f
Revises: 854629751977
Create Date: 2025-12-19 13:23:21.211167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f76ea5b82f'
down_revision: Union[str, Sequence[str], None] = '854629751977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('archive_path', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('storage_location', sa.String(length=20), nullable=False, server_default='local'))
    op.create_index(op.f('ix_documents_storage_location'), 'documents', ['storage_location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_storage_location'), table_name='documents')
    op.drop_column('documents', 'storage_location')
    op.drop_column('documents', 'archive_path')
    # ### end Alembic commands ###
